<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<RootNamespace>GitFormula_1</RootNamespace>
	  <UserSecretsId>eb7d874f-d900-430d-8053-2b429d909e4f</UserSecretsId>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.19" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		  <PrivateAssets>all</PrivateAssets>
		</PackageReference>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Controllers\" />
		<Folder Include="Constants\" />
		<Folder Include="Interfaces\Repositories\" />
		<Folder Include="Interfaces\Services\" />
		<Folder Include="Models\" />
		<Folder Include="DTO\" />
		<Folder Include="Repositories\" />
		<Folder Include="Services\" />
	</ItemGroup>

</Project>