// <auto-generated />
using System;
using GitFormula_1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GitFormula_1.Migrations
{
    [DbContext(typeof(GitFormula1DbContext))]
    partial class GitFormula1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GitFormula_1.Models.Badge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Badges");
                });

            modelBuilder.Entity("GitFormula_1.Models.DuelRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProfileAId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfileAScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileBId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProfileBScore")
                        .HasColumnType("integer");

                    b.Property<string>("ShareSlug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("WinnerProfileId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProfileAId");

                    b.HasIndex("ProfileBId");

                    b.HasIndex("WinnerProfileId");

                    b.ToTable("DuelRecords");
                });

            modelBuilder.Entity("GitFormula_1.Models.GitHubProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AccountCreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<DateTime>("CacheExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("FetchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PrimaryLanguage")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("GitHubProfiles");
                });

            modelBuilder.Entity("GitFormula_1.Models.ProfileBadge", b =>
                {
                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EarnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ProfileId", "BadgeId");

                    b.HasIndex("BadgeId");

                    b.ToTable("ProfileBadges");
                });

            modelBuilder.Entity("GitFormula_1.Models.RawGitHubStats", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CodeReviews")
                        .HasColumnType("integer");

                    b.Property<int>("CollabContributions")
                        .HasColumnType("integer");

                    b.Property<int>("CommitsLastYear")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentStreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("Followers")
                        .HasColumnType("integer");

                    b.Property<int>("IssuesClosed")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageBreakdownJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LifetimeContributions")
                        .HasColumnType("integer");

                    b.Property<int>("LongestStreakDays")
                        .HasColumnType("integer");

                    b.Property<int>("MergedPullRequests")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("RawContributionCalendarJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StarsEarned")
                        .HasColumnType("integer");

                    b.Property<int>("TopRepoStars")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("RawGitHubStats");
                });

            modelBuilder.Entity("GitFormula_1.Models.ScoreCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AlgorithmVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Defense")
                        .HasColumnType("integer");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("Mentality")
                        .HasColumnType("integer");

                    b.Property<int>("Offense")
                        .HasColumnType("integer");

                    b.Property<int>("Overall")
                        .HasColumnType("integer");

                    b.Property<int>("Pace")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uuid");

                    b.Property<int>("Racecraft")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId")
                        .IsUnique();

                    b.ToTable("ScoreCards");
                });

            modelBuilder.Entity("GitFormula_1.Models.DuelRecord", b =>
                {
                    b.HasOne("GitFormula_1.Models.GitHubProfile", "ProfileA")
                        .WithMany()
                        .HasForeignKey("ProfileAId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GitFormula_1.Models.GitHubProfile", "ProfileB")
                        .WithMany()
                        .HasForeignKey("ProfileBId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GitFormula_1.Models.GitHubProfile", "WinnerProfile")
                        .WithMany()
                        .HasForeignKey("WinnerProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ProfileA");

                    b.Navigation("ProfileB");

                    b.Navigation("WinnerProfile");
                });

            modelBuilder.Entity("GitFormula_1.Models.ProfileBadge", b =>
                {
                    b.HasOne("GitFormula_1.Models.Badge", "Badge")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GitFormula_1.Models.GitHubProfile", "Profile")
                        .WithMany("ProfileBadges")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GitFormula_1.Models.RawGitHubStats", b =>
                {
                    b.HasOne("GitFormula_1.Models.GitHubProfile", "Profile")
                        .WithOne("RawStats")
                        .HasForeignKey("GitFormula_1.Models.RawGitHubStats", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GitFormula_1.Models.ScoreCard", b =>
                {
                    b.HasOne("GitFormula_1.Models.GitHubProfile", "Profile")
                        .WithOne("ScoreCard")
                        .HasForeignKey("GitFormula_1.Models.ScoreCard", "ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("GitFormula_1.Models.Badge", b =>
                {
                    b.Navigation("ProfileBadges");
                });

            modelBuilder.Entity("GitFormula_1.Models.GitHubProfile", b =>
                {
                    b.Navigation("ProfileBadges");

                    b.Navigation("RawStats");

                    b.Navigation("ScoreCard");
                });
#pragma warning restore 612, 618
        }
    }
}
